# .github/workflows/rosti_deploy.yml

name: Deploy into Roští.cz

on:
    push:
      branches: [main]

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        HOST: ssh.rosti.cz
        USER: app
        PORT: 26742
        NODE_VERSION: 19.9.0
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "v19.9.0"
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ROSTI_DEPLOY_SSH_KEY }}
      - name: Setup hostkey
        run: |
          echo "ssh.rosti.cz ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcEf/45OKt/NekZUAU/VVnFCwY243LQ3QkUb6y1lhOHGSnA0WjJ3qQ3UE4nhi+eGJlT5jSgoQs1XFvT4wLyR2wp2NwixZqyjoOAYt1Gln+P3iqx9jz7IEHZQtUM//WbhOLwCdsnNOYNlcGZBUfrvFPwwn/LIXUYlaeiGyD9PMy2O0hBGSlSdJOii4vy9SyiCmNM87foyOpAlhUjMiQP5IYMBnk5gMGGfOo4LJ+e8j9N+oIqVsaIFTed5Ok7DGuR3EHQDGt6lX9Ee7f+rENasx7xIrFadxBo8XUWQe5zNampNj32UviClKgrPm/FFHfh1O11+Q8ymlZRdYRG+bJ5eV7" > ./known_hosts
      - name: env
        run: |
          cat << EOF > .env
          ${{ secrets.ENV }}
          EOF
      - name: Dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Setup Node.js
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST /usr/local/bin/rosti node $NODE_VERSION
      - name: Setup Supervisord
        run: |
          cat << EOF > rosti.app.conf
          [program:app]
          command=/srv/bin/primary_tech/npm start
          environment=PATH="/srv/bin/primary_tech:/usr/local/bin:/usr/bin:/bin:/srv/.npm-packages/bin"
          stopasgroup=true
          directory=/srv/app
          process_name=app
          autostart=true
          autorestart=true
          stdout_logfile=/srv/log/node.log
          stdout_logfile_maxbytes=2MB
          stdout_logfile_backups=5
          stdout_capture_maxbytes=2MB
          stdout_events_enabled=false
          redirect_stderr=true
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.app.conf $USER@$HOST:/srv/conf/supervisor.d/app.conf
          rm rosti.app.conf
      - name: Setup Nginx
        run: |
          cat << EOF > rosti.nginx.conf
          server {
              listen       0.0.0.0:8000;
              listen       [::]:8000;
              location / {
                      proxy_pass         http://127.0.0.1:8080/;
                      proxy_redirect     default;
                      proxy_set_header   X-Real-IP  \$remote_addr;
                      proxy_set_header   Host       \$host;
              }
              location /static/ {
                      alias /srv/app/public/;
              }
          }        
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.nginx.conf $USER@$HOST:/srv/conf/nginx.d/app.conf
          rm rosti.nginx.conf
      - name: Copy code
        run: |
          rsync -ae "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" --delete-after --exclude=.git ./ $USER@$HOST:/srv/app/
      - name: Apply changes
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl reread
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart app
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart nginx
